### ISSUE TITLE
Est-ce que votre API est tjrs Opée ?

### ISSUE THREAD

**Issue by mistertest** [leeroybrun/node-allocine-api#6]
Bonjour,
J'ai fait beaucoup de recherches pour tenter de trouver des api non officielle Allociné qui fonctionnent toujours. La tienne fonctionne-t-elle encore ?
Merci beaucoup pour le partage.

Cordialement.

**Comment by leeroybrun** [comment]
Hello,

Désolé pour le retard.

Je n'utilises plus spécialement ce projet, mais il faut essayer ;-)

Normalement il devrait toujours fonctionner.

A+

**Comment by mistertest** [comment]
Merci, je testerais.
